### ISSUE TITLE
Installation fails on bionic VMs, OS lacks libfuse3-dev

### ISSUE THREAD

**Issue by maxxer** [gael-ian/vagrant-bindfs#104]
Excerpt of the provisioning for a "bionic" vm:
```
==> web: Bindfs seems to not be installed on the virtual machine, installing now
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

apt-get install -y build-essential pkg-config wget tar libfuse3-dev

Stdout from the command:

Reading package lists...
Building dependency tree...
Reading state information...


Stderr from the command:

E: Unable to locate package libfuse3-dev

```

https://packages.ubuntu.com/search?keywords=libfuse3-dev

**Comment by gael-ian** [comment]
Hi @maxxer 

Ubuntu 18.04, known as Bionic Beaver, is now 5 years old and, even if it was a version with long-term support, it is now out of maintenance since a few months. If you can, it can be a good idea to upgrade to a more recent version of Ubuntu (as Jammy Jellyfish, the new LTS that will be supported until 2032).

If you can't upgrade, you can still install a previous version of vagrant-bindfs with `vagrant plugin install vagrant-bindfs --plugin-version 1.1.9`.

libfuse 3 support was brought by vagrant-bindfs 1.2. The 1.1 serie will use libfuse 2.

Is that OK for you?

**Comment by maxxer** [comment]
Fine, thank you very much for the response!!
