### ISSUE TITLE
installation fail on vagrant v2.0.0

### ISSUE THREAD

**Issue by gusdecool** [gael-ian/vagrant-bindfs#76]
Installation of this plugin is fail on vagrant  v2.0.0

here is the copy of running command

```bash
$ vagrant plugin install vagrant-bindfs
Installing the 'vagrant-bindfs' plugin. This can take a few minutes...
Fetching: vagrant-bindfs-1.0.9.gem (100%)
Fetching: vagrant-share-1.1.9.gem (100%)
Fetching: micromachine-2.0.0.gem (100%)
Fetching: vagrant-vbguest-0.14.2.gem (100%)
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: user requested 'vagrant-share (= 1.1.7)'
```

tested using MAC OSX v10.12.6 (16G29)

**Comment by gael-ian** [comment]
Hi @gusdecool 

As there's no explicit dependency between neither `vagrant-bindfs` nor `vagrant-vbguest` to `vagrant-share`, I guess it's an internal plugin automatically loaded by Vagrant. It's last release is tagged 1.1.9 and dated from more than one year ago, hence it sounds strange that Vagrant 2.0.0 would require `vagrant-share` 1.1.7.

Did you upgraded an old version of Vagrant to 2.0.0 or is it a fresh install?
Did you try to reinstall Vagrant?

I'll did deeper as soon as I can but this issue seems to be more related to Vagrant than to this plugin.

Thanks for reporting

**Comment by gusdecool** [comment]
Hi @gael-ian i was updating from vagrant 1.9.x to 2.0.0. 
i guess there is something dependecies from 1.9.x causing the issue.

I will try the reinstall method and will let you know the result.

Cheers 😃

**Comment by gael-ian** [comment]
Hi @gusdecool,

You can try to remove the `~/.vagrant.d/` directory and reinstall Vagrant. It seems to work, see issue #8978.

We're still looking for the problem's origin.

Sorry for that

**Comment by gael-ian** [comment]
Hi,

After verifications, there's no breaking change in Vagrant 1.9.8 or Vagrant 2.0.0 that require a fix in `vagrant-bindfs`. This issue seems to be related to the internal plugin [`vagrant-share`](https://www.vagrantup.com/docs/share/).

The issue [hashicorp/vagrant#8978](https://github.com/hashicorp/vagrant/issues/8978) has already been assigned to someone (I guess) working for HashiCorp and should be addressed as soon as possible. 

Meanwhile, the solution seems to be:

- Uninstall Vagrant
- Remove `~/.vagrant.d`
- Reinstall Vagrant

**Comment by gusdecool** [comment]
awesome, thanks for the info @gael-ian 😄 👍

**Comment by gusdecool** [comment]
hi @gael-ian , just for info. after i remove `~/.vagrant.d` and then reinstall vagrant bindfs as you suggested. installation is succesfull 👍

**Comment by gael-ian** [comment]
@gusdecool Glad to ear it, thanks :)
